# Generated by Django 5.2.4 on 2025-08-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Статус оповещения')),
                ('sent_channel', models.CharField(blank=True, choices=[('email', 'Email'), ('sms', 'SMS'), ('telegram', 'Telegram')], max_length=20, null=True, verbose_name='Канал отправки оповещения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('error_log', models.TextField(blank=True, null=True, verbose_name='Журнал ошибок')),
            ],
            options={
                'verbose_name': 'Оповещение',
                'verbose_name_plural': 'Оповещения',
                'ordering': ['-created_at'],
            },
        ),
    ]
